swagger: "2.0"
info:
  description: "This is an api to manage members"
  version: "1.0.0"
  title: "Swagger Members"
host: "members.swagger.io"
basePath: "/v2"
tags:
- name: "member"
  description: "Everything about member"
schemes:
- "https"
- "http"
paths:
  /member:
    post:
      tags:
      - "member"
      summary: "Add a new member"
      description: ""
      operationId: "addMember"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Member object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/Member"
      responses:
        405:
          description: "Invalid input"
    get:
      tags:
      - "member"
      summary: "List Members"
      description: "List of members"
      operationId: "listMembers"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Member"
        400:
          description: "Invalid status value"
  /member/{memberId}:
    get:
      tags:
      - "member"
      summary: "Find member by ID"
      description: "Returns a single member"
      operationId: "getMemberById"
      produces:
      - "application/json"
      parameters:
      - name: "memberId"
        in: "path"
        description: "ID of member to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Member"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Member not found"
    put:
      tags:
      - "member"
      summary: "Updates a member in the database"
      description: ""
      operationId: "updateMember"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "memberId"
        in: "path"
        description: "ID of member that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Member object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/Member"
      responses:
        405:
          description: "Invalid input"
    delete:
      tags:
      - "member"
      summary: "Deletes a member"
      description: ""
      operationId: "deleteMember"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "memberId"
        in: "path"
        description: "Member id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Member not found"

definitions:
  Member:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: object
        properties:
          name:
            type: string
          value:
            type: string
      gender:
        type: string
        format: string
      name:
        type: object
        properties:
          title:
            type: string
          first:
            type: string
          last:
            type: string
      location:
        type: object
        properties:
          street:
            type: string
          city:
            type: string
          state:
            type: string
          postcode:
            type: string
          coordinates:
            type: object
            properties:
              offset:
                type: number
              description:
                type: string
          timezone:
            type: object
            properties:
              latitude:
                type: number
              longitude:
                type: number
      email:
        type: string
      login:
        type: object
        properties:
          uuid:
            type: string
          username:
            type: string
          password:
            type: string
          salt:
            type: string
          md5:
            type: string
          sha1:
            type: string
          sha256:
            type: string
      dob:
        type: object
        properties:
          date:
            type: string
          age:
            type: number
      registered:
        type: object
        properties:
          date:
            type: string
          age:
            type: number
      phone:
        type: string
      cell:
        type: string
      picture:
        type: object
        properties:
          large:
            type: string
          medium:
            type: string
          thumbnail:
            type: string
      nat:
        type: string
  
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"